In [1]:
import pdfplumber
import pandas as pd
import numpy as np

In [2]:
import re

In [3]:
from collections import Counter

In [4]:
path = 'D:/Downloads/shivamQ2.pdf'

In [5]:
file1 = 'D:/Downloads/shivamBefore.pdf'

In [6]:
def duplicate_handler(series):
    things = Counter(series)
    for key, value in things.items():
        if value > 1:
            toHandle = key

    return series[series == toHandle].index.tolist()

In [7]:
s = pd.Series(['Alice', 'Bob', 'Alice', 'Charlie'])

print(s[s == 'Alice'].index)
print(duplicate_handler(s))

Index([0, 2], dtype='int64')
[0, 2]

In [87]:
def financial_statements(filePath):

    finalThings = list()
    
    with pdfplumber.open(filePath) as pdf:
        pages = pdf.pages
        wholePage = pages[0].extract_text()
        statements = wholePage.split('udited Statement of ')
        
        for statement in statements:
            dataList = []
            lines = statement.split('\n')
            metricName = None
            headersNotFound = True
            sectionName = None
            #print(statement)
            thCounter = 0
            for ind, line in enumerate(lines):
                if ind == 0:
                    title = line
                    print(title)
                if headersNotFound:
                    if line.strip() == "Particulars":
                        line = line + ' ' + lines[ind + 1]
                    headingCheck = re.findall(r'^(\d\d)[\D]+\s', line)
                    if ('Particulars' in line and line.strip() != 'Particulars' and not metricName) or headingCheck:
                        words = line.split(' ')
                        metricName = words.pop(0)
                        print(words)
                        for word in words:
                            print(word)
                            if 'th ' in word or 'rd ' in word:
                                thCounter += 1
                        if thCounter == 0:
                            thCounter = 2
                        print('==============thCounter=============', thCounter)
                        joiningIndex = int(len(words) / thCounter)
                        firstDate = ' '.join(words[:joiningIndex])
                        secondDate = ' '.join(words[joiningIndex:])
                        headersNotFound = False
                else:
                    print(line)
                    rePattern = r'^([\D ]+)\s+(\(?[\d,\)]+\)?|-)?\s+(\(?[\d,]+\)?|-)?$'
                    rePattern2 = r'^([\D ]+)\s+(\(?[\d,\)]+\)?|-)?\s+(\(?[\d,]+\)?|-)?\s+(\(?[d,]+\)?)$'
                    regexPattern = re.findall(rePattern, line)
                    if ind != len(lines) - 1:
                        if ind > 0 and 'Total' in lines[ind - 1] and 'Total' not in line and 'Financial Position' in title:
                            sectionName = line.strip(': ')
                        elif not regexPattern and re.findall(rePattern, lines[ind+1]) and len(line.split(' ')) < 5:
                            sectionName = line.strip(': ')
                        #elif not regexPattern and len(line.split(' ')) < 4:
                            #sectionName = line.strip(': ')
                    if not regexPattern:
                        regexPattern = re.findall(rePattern2, line)
                    if regexPattern:
                        valuesTemp = regexPattern[0]
                        print(regexPattern)
                        dataList.append({'section': sectionName,
                                        metricName: valuesTemp[0],
                                        firstDate: valuesTemp[1],
                                        secondDate: valuesTemp[2]})
            if dataList:
                dataFrame = pd.DataFrame(dataList)
                duplicates = dataFrame['Particulars'].duplicated(keep=False)
                trueSeries = dataFrame['section'] + '_' + dataFrame['Particulars']
                newOnes = pd.Series(np.where(duplicates, trueSeries, dataFrame['Particulars']))
                newDuplicates = newOnes.duplicated()
                #print(f'new things: {newOnes}')
                repeatedGroups = newOnes.groupby(newOnes).cumcount()
                numberNames = newOnes + '_' + repeatedGroups.astype(str)
                newOnes = np.where(repeatedGroups, numberNames, newOnes) 
                dataFrame['Particulars'] = newOnes
                dataFrame['Particulars'] = pd.Categorical(dataFrame['Particulars'], ordered=True) 
                dataFrame.columns.name = title
                finalThings.append(dataFrame)
                print('=============================DATAFRAME MADE=================================')
            else:
                print('==============================datalist if empty==============================')

    return finalThings

In [88]:
balanceSheet1 = financial_statements(path)
print(len(balanceSheet1))
balanceSheet1[0].head(40)

SHIVAM CEMENTS LIMITED
==============================datalist if empty==============================
Financial Position
['16th', 'July', '2025', '15th', 'July', '2024']
16th
July
2025
15th
July
2024
==============thCounter============= 2
(Ashad 32, 2082) (Ashad 31, 2081)
Assets
Non Current Assets
Property, Plant & Equipment 3,885,988,681 3,613,074,969
[('Property, Plant & Equipment', '3,885,988,681', '3,613,074,969')]
Intangible Assets 11,303,875 3,396,234
[('Intangible Assets', '11,303,875', '3,396,234')]
Investment in Quoted Shares 131,208,000 119,280,000
[('Investment in Quoted Shares', '131,208,000', '119,280,000')]
Investment in Subsidiaries 4,755,208,800 4,585,208,800
[('Investment in Subsidiaries', '4,755,208,800', '4,585,208,800')]
Other Non-Current Assets 37,123,251 34,464,296
[('Other Non-Current Assets', '37,123,251', '34,464,296')]
Total Non Current Assets 8,820,832,606 8,355,424,299
[('Total Non Current Assets', '8,820,832,606', '8,355,424,299')]
Current Assets
Inventories 1,735,417,180 1,874,856,439
[('Inventories', '1,735,417,180', '1,874,856,439')]
Financial Assets
Trade Receivables 819,967,247 1,126,644,809
[('Trade Receivables', '819,967,247', '1,126,644,809')]
Cash & Cash Equivalent 651,816,544 240,488,471
[('Cash & Cash Equivalent', '651,816,544', '240,488,471')]
Bank Balance (Other than Cash & Cash Equivalent) 400,000,000 200,000,000
[('Bank Balance (Other than Cash & Cash Equivalent)', '400,000,000', '200,000,000')]
Others Financial Assets 26,474,068 34,166,166
[('Others Financial Assets', '26,474,068', '34,166,166')]
Other Current Assets 137,570,571 123,901,482
[('Other Current Assets', '137,570,571', '123,901,482')]
Income Tax Assets (Net) 6,198,709 15,396,894
[('Income Tax Assets (Net)', '6,198,709', '15,396,894')]
Total Current Assets 3,777,444,319 3,615,454,260
[('Total Current Assets', '3,777,444,319', '3,615,454,260')]
Total Assets 12,598,276,925 11,970,878,560
[('Total Assets', '12,598,276,925', '11,970,878,560')]
Equity & Liabilities
Equity
Equity Share Capital 5,456,808,500 5,027,000,000
[('Equity Share Capital', '5,456,808,500', '5,027,000,000')]
Share Premium Reserve 956,233,911 956,233,911
[('Share Premium Reserve', '956,233,911', '956,233,911')]
Other Reserve & Surplus 3,876,756,428 3,509,621,193
[('Other Reserve & Surplus', '3,876,756,428', '3,509,621,193')]
Total Equity 10,289,798,839 9,492,855,104
[('Total Equity', '10,289,798,839', '9,492,855,104')]
Non Current Liabilities
Financial Liabilities
Long Term Borrowings 1,738,963 4,710,093
[('Long Term Borrowings', '1,738,963', '4,710,093')]
Other Financial Liabilities 12,160,661 3,432,662
[('Other Financial Liabilities', '12,160,661', '3,432,662')]
Deferred Tax Liabilities 200,342,221 158,457,390
[('Deferred Tax Liabilities', '200,342,221', '158,457,390')]
Total Non Current Liabilities 214,241,845 166,600,146
[('Total Non Current Liabilities', '214,241,845', '166,600,146')]
Current Liabilities
Financial Liabilities
Trade Payables 1,522,272,214 1,710,448,293
[('Trade Payables', '1,522,272,214', '1,710,448,293')]
Short Term Borrowings 8,428,150 68,499,786
[('Short Term Borrowings', '8,428,150', '68,499,786')]
Other Financial Liabilities 113,050,483 48,481,990
[('Other Financial Liabilities', '113,050,483', '48,481,990')]
Other Current Liabilities 436,055,236 472,284,847
[('Other Current Liabilities', '436,055,236', '472,284,847')]
Provisions 14,430,158 11,708,394
[('Provisions', '14,430,158', '11,708,394')]
Total Current Liabilities 2,094,236,240 2,311,423,310
[('Total Current Liabilities', '2,094,236,240', '2,311,423,310')]
Total Liabilities 2,308,478,086 2,478,023,456
[('Total Liabilities', '2,308,478,086', '2,478,023,456')]
Total Equity and Liabilities 12,598,276,925 11,970,878,560
[('Total Equity and Liabilities', '12,598,276,925', '11,970,878,560')]
Una
=============================DATAFRAME MADE=================================
Profit & Loss
['Upto', '4', 'Qtr', '2081-82', 'Upto', '4', 'Qtr', '2080-81']
Upto
4
Qtr
2081-82
Upto
4
Qtr
2080-81
==============thCounter============= 2
Upto 4 Qtr 2081-82 Upto 4 Qtr 2080-81
Income:
Revenue From Operations 7,764,296,397 7,704,060,749
[('Revenue From Operations', '7,764,296,397', '7,704,060,749')]
Cost of Sales 6,034,917,807 6,664,127,188
[('Cost of Sales', '6,034,917,807', '6,664,127,188')]
Gross Profit 1,729,378,590 1,039,933,561
[('Gross Profit', '1,729,378,590', '1,039,933,561')]
Other Income 139,400,548 201,389,534
[('Other Income', '139,400,548', '201,389,534')]
Expenses:
Administration Expenses 275,136,138 226,519,321
[('Administration Expenses', '275,136,138', '226,519,321')]
Selling and Distribution Expenses 655,346,246 680,342,625
[('Selling and Distribution Expenses', '655,346,246', '680,342,625')]
Finance Cost 10,186,913 49,696,776
[('Finance Cost', '10,186,913', '49,696,776')]
Total Expenses 940,669,296 956,558,723
[('Total Expenses', '940,669,296', '956,558,723')]
Profit/(Loss) Before Tax 928,109,842 284,764,372
[('Profit/(Loss) Before Tax', '928,109,842', '284,764,372')]
Current Tax 100,734,155 2,051,476
[('Current Tax', '100,734,155', '2,051,476')]
Deferred Tax 33,267,683 23,075,218
[('Deferred Tax', '33,267,683', '23,075,218')]
Net Profit/(Loss) For The Year 794,108,004 259,637,678
[('Net Profit/(Loss) For The Year', '794,108,004', '259,637,678')]
Una
=============================DATAFRAME MADE=================================
Comprehensive Income
['Upto', '4', 'Qtr', '2081-82', 'Upto', '4', 'Qtr', '2080-81']
Upto
4
Qtr
2081-82
Upto
4
Qtr
2080-81
==============thCounter============= 2
Upto 4 Qtr 2081-82 Upto 4 Qtr 2080-81
Net Profit/(Loss) For The Year 794,108,004 259,637,678
[('Net Profit/(Loss) For The Year', '794,108,004', '259,637,678')]
Other Comprehensive Income
Gain/(Loss) on Investment in equity instruments measured at fair value 11,928,000 (15,506,400)
[('Gain/(Loss) on Investment in equity instruments measured at fair value', '11,928,000', '(15,506,400)')]
Tax Relating to Components of Other Comprehensive Income 8,617,148 16,091,452
[('Tax Relating to Components of Other Comprehensive Income', '8,617,148', '16,091,452')]
Total Other Comprehensive Income (OCI) 3,310,852 (31,597,852)
[('Total Other Comprehensive Income (OCI)', '3,310,852', '(31,597,852)')]
Total Comprehensive Income (TCI) 797,418,856 228,039,826
[('Total Comprehensive Income (TCI)', '797,418,856', '228,039,826')]
Notes: 1) Figures presented above may vary with the audited figures if instructed by regulators and/or statutory auditors.
2) Figures are regrouped/rearranged/restated wherever necessary for consistent presentation of financial statement.
3) Depreciation has been classified & identified as according to the functional classification and charged to Cost of Sales
& Administrative Expenses in both Periods.
4) Last year figure is of audited financial statement.
lwtf]kq btf{ tyf lgisfzg lgodfjnL @)&# sf] cg';"lr !$
-lgod @^ sf] pklgod -!_ ;“u ;DalGwt_ cf=j= @)*!.)*@ sf] rf}yf] q}dfl;s k|ltj]bg
!= ljQLo ljj/0fM
-s_ rf}yf] q}dfl;s ;Ddsf] jf;nft, gfkmf—gf]S;fg ;DaGwL ljj/0fM
o; cjwLsf] ;Da4 ;+:yfx?;+u ePsf] sf/f]jf/sf] ljj/0f lgDg cg';f/ /x]sf] 5 M
-v_ k|d'v laQLo cg'kftx?M
sf/f]jf/ /sd -d"=c= s/ afx]s_
qm=;+= ;Da4 ;+:yfx?sf] gfd
vl/b ljlqm k|lt k|ltz]o/ k||ltz]o/ s"n
! df]8{g O{Gkmfi6«Sr/ k|f=ln= 509,775,789.00 0 z]o/ cfDbfgL g]6jy{ ;DklQsf] t/ntf
@ c/ljGb ODkf]l/od k|f=ln= 437,865,211.00 0 -jflif{s ?=_ ?= d"No ?= cg'kft
# sG:6«Szg ;f]n'zg k|f=ln= 867,199.00 0
$ lk|ldo/ jfo/ k|f=ln= 663,137.00 0 14.55 188.57 230.87 1.80
% kz'klt l;GKofs O08li6«h k|f=ln= 30,948,685.00 0
^ OGk|mf6]s k|f=ln= 258,407.00 0
& nIdL nfO{d k|f]8S;\ 0.00 2,903,637.00
* ;]Gr'/L l;d]G6\; k|f=ln= 58,616,986.00 0
( bGtsfnL Sj]l/h k|f=ln= 49,446,310.00 0
!) ln6d; OG8li6«h k|f=ln= 394,213.00 2,700,324.00
!! nSsL g]kfn sDkgL k|f=ln= 9,217,128.00 0
!@ lzjd\ xf]lN8ª\; ln= 2,661,281.00 2,280,000.00
!# xf]ª\;L lzjd\ l;d]G6 k|f= ln 1,084,987,014.00
@= Joj:yfksLo ljZn]if0f M
s_ o; cjlwdf ;+:yfsf]] t/ntf nufotsf cGo s'/fx? ;Gtf]ifhgs /x]sf 5g\ .
v_ cfufdL cjlwsf] Joj;flos of]hgf ;DaGwdf Joj:yfkgsf] ljZn]if0ffTds ljj/0fM
;+:yfsf] p2]Zo cg';f/ pTkfbg / ljqmL ljt/0f u/L pkef]Qmfx?nfO{ pRr u'0f:t/sf] l;d]G6 cfk"lt{ u/L d'gfkmf cfh{g ug]{ ;DalGw sfo{x? ug'{sf ;fy} ;dofg's'n Joj;flos sfo{of]hgfsf] th'{df
tyf ;f] sf] sfof{Gjog ug]{ nufotsf sfo{df ;+:yf k|ltj4 /x]sf] 5 .
u_ ljutsf] cg'ejaf6 ;+ul7t ;+:yfsf] df}Hbft, gfkmf jf gub k|jfxdf tflTjs c;/ kfg{ ;Sg] 36gf, cj:yf cfbL ePdf ;f] ;DalGw ljZn]if0ffTds ljj/0fM
ljsf; lgdf{0fsf sfddf nfdf] ;do b]lv l;lyntf cfPsf], g]kfndf dfusf] t'ngfdf l;d]G6sf] pTkfbg cToflws /x]sf] kl/j]znfO{ ;d]t Wofgdf /fvL ahf/ k|j{4{g / ahf/ lj:tf/;+u ;DalGwt
sfo{x?nfO{ cem k|efjsf/L ?kdf ;~rfng ug{] gLlt cjnDag ub}{ u|fxs ;+/If0f gLltnfO{ sfod} /fvL cfFpbf lbgdf c;/ kfg{ ;Sg] 36gf jf cj:yf cfpg glbg cfjZos ;t{stf ckgfO{
p2]Zo adf]lhdsf sfdx? ;+rfng ub{} cl3 a9\g] gLlt lnOPsf] 5 . ;+:yfsf] df}Hbft, gub k|jfx nufotsf s'/fx?df tflTjs c;/ kg{ ;Sg] 36gf cj:yf 5}g . ljsf; lgdf{0fsf sfo{df a9f]Q/L
eO{ cf}Bf]lus pTkfbg clea[l4 / d'gfkmf cfh{gdf ;sf/fTds k|efj kg]{5 eGg] ljZjf; lnPsf 5f}+ .
#= sfg"gL sf/jfxL ;DalGw ljj/0fM -o; ;+:yfn] jf ;+:yfsf] lj?4 s'g} d'2f bfo/ ePsf] eP ;f]sf] hfgsf/L_M–
-s_ cfkm\gf] Joj;fo;+u ;DalGwt sf/f]jf/, vr{ nufotsf ljifodf eP u/]sf s]xL lz{ifsdf >L 7"nf s/bftf sfof{noaf6 hf/L ePsf ;+zf]lwt s/ lgwf{/0f cfb]zsf lj?4 sDkgLn] k|zf;sLo
k'g/fjnf]sgsf nflu cfGtl/s /fh:j ljefusf dxflgb{]zsHo" ;dIf tyf >L /fh:j Gofoflws/0f sf7df8f}+ ;dIf k'g/fj]bg u/]sf]df ;f] ljifox? ljrf/flwg /x]sf 5g .
-v_ o; sDkgLnfO{ ljutdf g]kfn ljB't k|flws/0fn] nf]8;]l8ªsf avt ljgf nf]8;]l8ª 8]l8s]6]8÷6«s+ nfO{gaf6 ljB't ;]jf glbPsf], glnPsf] ePtf klg kqfrf/ u/L 8]l8s]6]8 b/sf] yk dx;'n
5'6 /sd egL efu u/]sf] ;DaGwdf ljjfb sfod} /x]sf]df @)&@ df3 b]lv @)&% a}zfv;Ddsf] ljjflbt yk dx;'ndf lrQ ga'em]df g]kfn ljB't k|flws/0fsf] k'g/fjnf]sg ;ldlt ;dIf k'g/fj]
bg btf{ ug{ ;"rgf k|sfzg u/L Dofb cjlw tf]lsP adf]lhd o; sDkgLn] k|flws/0f ;dIf k'g/fjnf]sgsf] lgj]bg btf{ u/]sf]df xfn txfF ljrf/flwg /x]sf] 5 . pQm ljjfb k'gf/fjnf]sg ;ldltaf6
lg/f]k0f x'g] ljZjf; lnPsf] 5f}+ . ;fy} k|flws/0f ;+u ;DalGwt cGo # yfg l/6x? >L ;jf]{Rr cbfntdf ljrf/flwg /x]sf 5g\ .
-u_ sDkgLn] l;d]G6 laqmL ug{ lgo'Qm u/]sf ljt/s / l;d]G6 vl/bstf{ ;+:yfx?n] ;dodf /sd e'QmfgL gu/]sf] ljifodf To:tf s]lx ;+:yf Pad\ JolQm ;d]tsf lj?4 /sd c;'nLsf nflu >L sf7df8f}+
lhNnf cbfntdf lkm/fb bfo/ u/]sf]df s]xL d'Bfx? ljrf/flwg /x]sf 5g\ .
3_ jfudtL k|b]z ;/sf/sf] cfly{s P]g @)&& / )&* af6 l;d]G6sf] ljlqmdf )=@% k|ltzt ljlqm s/ ;/x k|fs[lts ;|f]t s/ nufpg] Joj:yf ;+ljwfg / ;+l3o sfg"g ;+u aflemPsf] x'Fbf P]gsf pQm
Joj:yf ab/ ug{ dfu u/L ;jf]{Rr cbfnt ;dIf l/6 lgj]bg bfo/ ePsf]df ljrf/flwg /x]sf 5g\ .
ª_ jg tyf e'–;+/If0f ljefun] r'g9'ª\ufsf] pTkfbg ubf{ vfgL tyf e'ue{ ljefudf bflvnf u/]sf] /f]olN6 /sdsf] @%Ü k|ltzt j/fj/ x'g] /sd jftfj/0f z'Ns jfkt e'QmfgL ug'{ ;d]t egL kqfrf/ u/]
sf]df pQm kqfrf/ vlgh kbfy{ P]g lgod / jg P]g, @)&^ ;d]tsf] ljkl/t dfu u/]sf]df sDkgLn] ;jf]{Rr cfbfntsf] ;+j}wflgs Ohnf; ;dIf pQm kq ;d]t ab/ ug{ dfu u/L /L6 lgj]bg u/]
sf]df cGtl/d cfb]z hf/L eO{ pQm d'2f ljrf/flwg /x]sf] 5 .
r_ s]lx ;+:yfx?n] lj1fkg s/ nufpg / ;+sng ug]{ :yfgLo txsf] clwsf/ 7]Ssf ;Demf}tfaf6 k|fKt ePsf] elg kqfrf/ u/L gu/]sf] lj1fkg ;d]tsf] dfu u/]sfdf kqx? ab/ u/L kfpg >L ;jf]{Rr
cbfnt ;dIf @ yfg /L6 lgj]bg btf{ u/fPsf]df xfn rln/x]sf] 5 .
5_ sDkgLsf s'g} klg ;+rfnssf lj?4 cfly{s ck/fw u/]sf] ljifodf s'g} d'4f bfo/ u/]sf] jf ePsf] jf/] s'g} hfgsf/L k|fKt ePsf] 5}g .
$= ;+:yfsf] z]o/ sf/f]jf/ tyf k|ult ljZn]if0fM
-s_ lwtf]kq ahf/df ePsf] o; ;+:yfsf] z]o/sf] sf/f]jf/ v'Nnf ahf/sf] l;4fGt cg'?k x'g] u/]sf]5 .
-v_ o; q}df; cjlwsf] z]o/sf] clwstd, Go"gtd, clGtd d"No, sf/f]jf/ ePsf] lbg / z]o/ sf/f]jf/ ;+Vof M
clwstd d"No ?= Go"gtd d"No ?= clGtd d"No ?= sf/f]jf/ lbg sf/f]jf/ z]o/ ;+Vof
563.0 495.00 535.04 63 9,074,123 yfg
%= ;d:of tyf r'gf}tLM
ljsf; lgdf{0f If]qsf sfo{x?df l;lyntf nfdf] ;dob]lv /lx /x]sf], dfusf] t'ngfdf g]kfndf l;d]G6sf] pTkfbg ug]{ pBf]ux?sf] Ifdtf cToflws /x]sf], ljsf; lgdf{0f;+u ;DaGwLt ;/sf/L kl/of]
hgfx?sf nflu 5'6\ofO{Psf] ah]6 cToGt} Go"g x'g]u/]sf], ljlgof]lht ljsf; lgdf{0fsf] ah]6 klg Go"g dfqfdf vr{ x'g] u/]sf], nufPtsf sf/0faf6 lgdf{0f ;fdu|L pTkfbg ug]{ pBf]ux?nfO{ ;sf/fTds c;/
ug]{ cj:yfdf tflTjs ;'wf/ gePsf] . ahf/df cfd u|fxsx? dfem o; ;+:yfsf] pTkfbgnfO{ k|efjzfnL agfO{ xfnsf] ahf/ lx:;f sfod} /fvL yk ahf/ lx:;f cf]u6\g ;f]xL cg'?ksf] gLlt, /0fgLlt
cjnDag ul/ ;+:yfn] laqmL kl5 pknJw u/fpg] lgMZf'Ns k|fljlws ;]jfx?sf] lj:tf/, dfgj ;+zfwgsf] bIftfdf clea[l4 / r':t Joj:yfkg, vr{df ldtJolotf ckgfO{ sfo{ ug]{ gLlt lnOPsf] 5 .
^= ;+:yfut ;'zf;gM
;+:yfut ;'zf;g clej[l4sf nflu ;+:yfsf] Joj:yfkg / cfGtl/s lgoGq0f k|0ffnL Jojl:yt ug{], cfGtl/s n]vfk/LIf0f sfo{nfO{ yk k|efjsf/L agfpg], sf/f]jf/nfO{ r':t, l56f], 5l/tf] agfpg sf/f]
jf/df cfs{lift x'g] P]g, sfg"g tyf lgodgsf/L lgsfoaf6 hf/L ePsf gLlt, lgb{]zgx? Kffngf u/L ;+:yf ;+rfng ul/Psf] 5 .
&= ;To tYotfsf ;DaGwdf k|jGw lgb]{zssf] pb\3f]if0fM
o; k|ltj]bgdf pNn]lvt hfgsf/L tyf ljj/0fx?sf] z'4tf ;DaGwdf d JolQmut ?kdf pQ/bfloTj lnG5' . ;fy} d of] pb\3f]if0f ub{5' sL d}n] hfg] a'em];Dd o; k|ltj]bgdf pNn]lvt ljj/0fx? ;To,
tYo / k"0f{ 5g . nufgLstf{nfO{ ;';"lrt lg0f{o lng cfjZos s'g} ljj/0f jf ;"rgf tyf hfgsf/Lx? n'sfO{Psf] 5}g .
=============================DATAFRAME MADE=================================
3

Financial Position,section,Particulars,16th July 2025,15th July 2024
0,Non Current Assets,"Property, Plant & Equipment","3,885,988,681","3,613,074,969"
1,Non Current Assets,Intangible Assets,"11,303,875","3,396,234"
2,Non Current Assets,Investment in Quoted Shares,"131,208,000","119,280,000"
3,Non Current Assets,Investment in Subsidiaries,"4,755,208,800","4,585,208,800"
4,Non Current Assets,Other Non-Current Assets,"37,123,251","34,464,296"
5,Non Current Assets,Total Non Current Assets,"8,820,832,606","8,355,424,299"
6,Current Assets,Inventories,"1,735,417,180","1,874,856,439"
7,Financial Assets,Trade Receivables,"819,967,247","1,126,644,809"
8,Financial Assets,Cash & Cash Equivalent,"651,816,544","240,488,471"
9,Financial Assets,Bank Balance (Other than Cash & Cash Equivalent),"400,000,000","200,000,000"
10,Financial Assets,Others Financial Assets,"26,474,068","34,166,166"
11,Financial Assets,Other Current Assets,"137,570,571","123,901,482"
12,Financial Assets,Income Tax Assets (Net),"6,198,709","15,396,894"
13,Financial Assets,Total Current Assets,"3,777,444,319","3,615,454,260"
14,Financial Assets,Total Assets,"12,598,276,925","11,970,878,560"
15,Equity,Equity Share Capital,"5,456,808,500","5,027,000,000"
16,Equity,Share Premium Reserve,"956,233,911","956,233,911"
17,Equity,Other Reserve & Surplus,"3,876,756,428","3,509,621,193"
18,Equity,Total Equity,"10,289,798,839","9,492,855,104"
19,Financial Liabilities,Long Term Borrowings,"1,738,963","4,710,093"
20,Financial Liabilities,Financial Liabilities_Other Financial Liabilities,"12,160,661","3,432,662"
21,Financial Liabilities,Deferred Tax Liabilities,"200,342,221","158,457,390"
22,Financial Liabilities,Total Non Current Liabilities,"214,241,845","166,600,146"
23,Financial Liabilities,Trade Payables,"1,522,272,214","1,710,448,293"
24,Financial Liabilities,Short Term Borrowings,"8,428,150","68,499,786"
25,Financial Liabilities,Financial Liabilities_Other Financial Liabilit...,"113,050,483","48,481,990"
26,Financial Liabilities,Other Current Liabilities,"436,055,236","472,284,847"
27,Financial Liabilities,Provisions,"14,430,158","11,708,394"
28,Financial Liabilities,Total Current Liabilities,"2,094,236,240","2,311,423,310"
29,Financial Liabilities,Total Liabilities,"2,308,478,086","2,478,023,456"
30,Financial Liabilities,Total Equity and Liabilities,"12,598,276,925","11,970,878,560"

In [16]:
balanceSheet2 = financial_statements(file1)[0]
balanceSheet2.head(40)

Financial Position,section,Particulars,17th Oct 2025,16th Oct 2024
0,Non Current Assets,"Property, Plant & Equipment","3,895,234,883","3,580,529,913"
1,Non Current Assets,Intangible Assets,"9,682,252","173,569"
2,Non Current Assets,Investment in Quoted Shares,"120,353,520","119,280,000"
3,Non Current Assets,Investment in Subsidiaries,"4,755,208,800","4,585,208,800"
4,Non Current Assets,Other Non-Current Assets,"36,523,251","37,520,160"
5,Non Current Assets,Total Non Current Assets,"8,817,002,705","8,322,712,442"
6,Current Assets,Inventories,"1,778,825,479","1,759,821,823"
7,Financial Assets,Trade Receivables,"974,268,125","1,183,443,478"
8,Financial Assets,Cash & Cash Equivalent,"267,362,547","184,825,856"
9,Financial Assets,Bank Balance (Other than Cash & Cash Equivalent),"650,000,000",-
10,Financial Assets,Others Financial Assets,"17,049,522","11,619,724"
11,Financial Assets,Other Current Assets,"415,861,378","265,343,771"
12,Financial Assets,Income Tax Assets (Net),-,"15,232,046"
13,Financial Assets,Total Current Assets,"4,103,367,052","3,420,286,697"
14,Financial Assets,Total Assets,"12,920,369,757","11,742,999,139"
15,Equity,Equity Share Capital,"5,456,808,500","5,027,000,000"
16,Equity,Share Premium Reserve,"956,233,911","956,233,911"
17,Equity,Other Reserve & Surplus,"4,073,978,902","3,531,841,062"
18,Equity,Total Equity,"10,487,021,313","9,515,074,973"
19,Financial Liabilities,Long Term Borrowings,"1,090,438","2,232,803"
20,Financial Liabilities,Financial Liabilities_Other Financial Liabilities,"12,160,661",-
21,Financial Liabilities,Deferred Tax Liabilities,"209,405,154","148,253,763"
22,Financial Liabilities,Total Non Current Liabilities,"222,656,253","150,486,566"
23,Financial Liabilities,Trade Payables,"1,550,722,764","1,555,807,778"
24,Financial Liabilities,Short Term Borrowings,"163,848,760","6,313,804"
25,Financial Liabilities,Financial Liabilities_Other Financial Liabilit...,"96,261,536","29,669,374"
26,Financial Liabilities,Other Current Liabilities,"373,890,666","474,077,710"
27,Financial Liabilities,Provisions,"16,013,244","11,568,935"
28,Financial Liabilities,Income Tax Liabilities (Net),"9,955,221",-
29,Financial Liabilities,Total Current Liabilities,"2,210,692,192","2,077,437,600"
30,Financial Liabilities,Total Liabilities,"2,433,348,445","2,227,924,167"
31,Financial Liabilities,Total Equity and Liabilities,"12,920,369,757","11,742,999,139"

In [11]:
balanceSheet2

Profit & Loss,section,Particulars,Upto 1 Qtr 2082-83,Upto 1 Qtr 2081-82
0,Income,Revenue From Operations,"1,533,309,617","1,406,380,579"
1,Income,Cost of Sales,"1,206,737,196","1,302,730,722"
2,Income,Gross Profit,"326,572,421","103,649,857"
3,Income,Other Income,"103,656,894","105,743,699"
4,Expenses,Administration Expenses,"61,879,452","48,041,806"
5,Expenses,Selling and Distribution Expenses,"131,702,941","138,594,633"
6,Expenses,Finance Cost,"3,212,745","2,762,198"
7,Expenses,Total Expenses,"196,795,139","189,398,636"
8,Expenses,Profit/(Loss) Before Tax,"233,434,176","19,994,920"
9,Expenses,Current Tax,"16,439,092","859,882"
10,Expenses,Deferred Tax,"7,326,216","6,335,886"
11,Expenses,Net Profit/(Loss) For The Year,"209,668,868","12,799,152"

In [17]:
pd.merge(balanceSheet1, balanceSheet2, on='Particulars', how='outer').sort_values('Particulars')

Financial Position,section_x,Particulars,16th July 2025,15th July 2024,section_y,17th Oct 2025,16th Oct 2024
0,Financial Assets,Bank Balance (Other than Cash & Cash Equivalent),"400,000,000","200,000,000",Financial Assets,"650,000,000",-
1,Financial Assets,Cash & Cash Equivalent,"651,816,544","240,488,471",Financial Assets,"267,362,547","184,825,856"
2,Financial Liabilities,Deferred Tax Liabilities,"200,342,221","158,457,390",Financial Liabilities,"209,405,154","148,253,763"
3,Equity,Equity Share Capital,"5,456,808,500","5,027,000,000",Equity,"5,456,808,500","5,027,000,000"
4,Financial Liabilities,Financial Liabilities_Other Financial Liabilities,"12,160,661","3,432,662",Financial Liabilities,"12,160,661",-
5,Financial Liabilities,Financial Liabilities_Other Financial Liabilit...,"113,050,483","48,481,990",Financial Liabilities,"96,261,536","29,669,374"
6,Financial Assets,Income Tax Assets (Net),"6,198,709","15,396,894",Financial Assets,-,"15,232,046"
7,NaN,Income Tax Liabilities (Net),NaN,NaN,Financial Liabilities,"9,955,221",-
8,Non Current Assets,Intangible Assets,"11,303,875","3,396,234",Non Current Assets,"9,682,252","173,569"
9,Current Assets,Inventories,"1,735,417,180","1,874,856,439",Current Assets,"1,778,825,479","1,759,821,823"
10,Non Current Assets,Investment in Quoted Shares,"131,208,000","119,280,000",Non Current Assets,"120,353,520","119,280,000"
11,Non Current Assets,Investment in Subsidiaries,"4,755,208,800","4,585,208,800",Non Current Assets,"4,755,208,800","4,585,208,800"
12,Financial Liabilities,Long Term Borrowings,"1,738,963","4,710,093",Financial Liabilities,"1,090,438","2,232,803"
13,Financial Assets,Other Current Assets,"137,570,571","123,901,482",Financial Assets,"415,861,378","265,343,771"
14,Financial Liabilities,Other Current Liabilities,"436,055,236","472,284,847",Financial Liabilities,"373,890,666","474,077,710"
15,Non Current Assets,Other Non-Current Assets,"37,123,251","34,464,296",Non Current Assets,"36,523,251","37,520,160"
16,Equity,Other Reserve & Surplus,"3,876,756,428","3,509,621,193",Equity,"4,073,978,902","3,531,841,062"
17,Financial Assets,Others Financial Assets,"26,474,068","34,166,166",Financial Assets,"17,049,522","11,619,724"
18,Non Current Assets,"Property, Plant & Equipment","3,885,988,681","3,613,074,969",Non Current Assets,"3,895,234,883","3,580,529,913"
19,Financial Liabilities,Provisions,"14,430,158","11,708,394",Financial Liabilities,"16,013,244","11,568,935"
20,Equity,Share Premium Reserve,"956,233,911","956,233,911",Equity,"956,233,911","956,233,911"
21,Financial Liabilities,Short Term Borrowings,"8,428,150","68,499,786",Financial Liabilities,"163,848,760","6,313,804"
22,Financial Assets,Total Assets,"12,598,276,925","11,970,878,560",Financial Assets,"12,920,369,757","11,742,999,139"
23,Financial Assets,Total Current Assets,"3,777,444,319","3,615,454,260",Financial Assets,"4,103,367,052","3,420,286,697"
24,Financial Liabilities,Total Current Liabilities,"2,094,236,240","2,311,423,310",Financial Liabilities,"2,210,692,192","2,077,437,600"
25,Equity,Total Equity,"10,289,798,839","9,492,855,104",Equity,"10,487,021,313","9,515,074,973"
26,Financial Liabilities,Total Equity and Liabilities,"12,598,276,925","11,970,878,560",Financial Liabilities,"12,920,369,757","11,742,999,139"
27,Financial Liabilities,Total Liabilities,"2,308,478,086","2,478,023,456",Financial Liabilities,"2,433,348,445","2,227,924,167"
28,Non Current Assets,Total Non Current Assets,"8,820,832,606","8,355,424,299",Non Current Assets,"8,817,002,705","8,322,712,442"
29,Financial Liabilities,Total Non Current Liabilities,"214,241,845","166,600,146",Financial Liabilities,"222,656,253","150,486,566"
30,Financial Liabilities,Trade Payables,"1,522,272,214","1,710,448,293",Financial Liabilities,"1,550,722,764","1,555,807,778"
31,Financial Assets,Trade Receivables,"819,967,247","1,126,644,809",Financial Assets,"974,268,125","1,183,443,478"

In [33]:
from pathlib import Path

folderPath = 'D:/shivamData'
files = [x for x in Path(folderPath).iterdir() if x.is_file()]
combinedData = []

for file in files:
    tempList = financial_statements(file)
    print('\n\ncurrent file:', file)
    display(tempList[0])
    combinedData.append(tempList)

combinedBalanceSheet = []
for ind, tables in enumerate(combinedData):
    balanceSheet = tables[0]
    if ind == 0:
        combinedBalanceSheet = balanceSheet
        continue
    combinedBalanceSheet = pd.merge(combinedBalanceSheet, balanceSheet, how='outer', on='Particulars')
    display(combinedBalanceSheet.head(40))
    print(combinedBalanceSheet.columns)

combinedBalanceSheet

current file: D:\shivamData\040d3-1st-quarter-financial-statement_fy-81-082.pdf

Financial Position,section,Particulars,"16th Oct 2024 (Ashoj 30, 2081)","17th Oct 2023 (Ashoj 30, 2080)"
0,Non-Current Assets,"Property, Plant & Equipment","3,580,529,913","3,128,084,485"
1,Non-Current Assets,Intangible Assets,"173,569","346,792"
2,Non-Current Assets,Investment in Quoted Shares,"119,280,000","128,822,400"
3,Non-Current Assets,Investment in Subsidiaries,"4,585,208,800","4,262,135,800"
4,Non-Current Assets,Other Non-Current Assets,"37,520,160","55,895,160"
5,Non-Current Assets,Total Non-Current Assets,"8,322,712,442","7,575,284,637"
6,Current Assets,Inventories,"1,759,821,823","1,879,253,130"
7,Financial Assets,Trade Receivables,"1,183,443,478","1,687,609,586"
8,Financial Assets,Cash & Cash Equivalent,"184,825,856","157,887,088"
9,Financial Assets,Others Financial Assets,"11,619,724","28,306,501"
10,Financial Assets,Other Current Assets,"265,343,771","504,940,679"
11,Financial Assets,Income Tax Assets (Net),"15,232,046",-
12,Financial Assets,Total Current Assets,"3,420,286,697","4,257,996,984"
13,Financial Assets,Total Assets,"11,742,999,139","11,833,281,621"
14,Equity,Equity Share Capital,"5,027,000,000","4,400,000,000"
15,Equity,Share Premium Reserve,"956,233,911","956,233,911"
16,Equity,Other Reserve & Surplus,"3,531,841,062","3,575,059,288"
17,Equity,Total Equity,"9,515,074,973","8,931,293,199"
18,Financial Liabilities,Long Term Borrowings,"2,232,803","4,677,120"
19,Financial Liabilities,Deferred Tax Liabilities,"148,253,763","74,723,958"
20,Financial Liabilities,Total Non-Current Liabilities,"150,486,566","79,401,078"
21,Financial Liabilities,Trade Payables,"1,555,807,778","1,437,053,019"
22,Financial Liabilities,Short Term Borrowings,"6,313,804","969,543,466"
23,Financial Liabilities,Other Financial Liabilities,"29,669,374","49,140,890"
24,Financial Liabilities,Other Current Liabilities,"474,077,710","355,153,346"
25,Financial Liabilities,Provisions,"11,568,935","5,410,570"
26,Financial Liabilities,Income Tax Liabilities (Net),-,"6,286,053"
27,Financial Liabilities,Total Current Liabilities,"2,077,437,600","2,822,587,345"
28,Financial Liabilities,Total Liabilities,"2,227,924,167","2,901,988,422"
29,Financial Liabilities,Total Equity and Liabilities,"11,742,999,139","11,833,281,621"

current file: D:\shivamData\3e778-3rd-quarter-financial-statement_fy079-80.pdf

Financial Position,section,Particulars,12th Apr 2024 14th,Jan 2024 13th Apr 2023
0,"Provisions 11,222,560 9,971,139 4,293,625",Income Tax Liabilities (Net) -,"6,588,117","13,666,900"

current file: D:\shivamData\52407-2nd-quarter-financial-statement_fy-81-082.pdf

Financial Position,section,Particulars,"13th Jan 2025 (Poush 29,2081)","14th Jan 2024 (Poush 29, 2080)"
0,Non-Current Assets,"Property, Plant & Equipment","3,588,707,282","3,606,040,403"
1,Non-Current Assets,Intangible Assets,"3,343,016","253,397"
2,Non-Current Assets,Investment in Quoted Shares,"143,136,000","121,665,600"
3,Non-Current Assets,Investment in Subsidiaries,"4,585,208,800","4,262,135,800"
4,Non-Current Assets,Other Non-Current Assets,"37,488,127","34,323,811"
5,Non-Current Assets,Total Non-Current Assets,"8,357,883,225","8,024,419,011"
6,Current Assets,Inventories,"1,641,894,802","1,700,696,213"
7,Financial Assets,Trade Receivables,"1,101,447,205","1,840,514,041"
8,Financial Assets,Cash & Cash Equivalent,"557,795,174","194,057,953"
9,Financial Assets,Others Financial Assets,"29,996,222","267,663,027"
10,Financial Assets,Other Current Assets,"243,056,345","306,224,294"
11,Financial Assets,Income Tax Assets (Net),"13,704,890",-
12,Financial Assets,Total Current Assets,"3,587,894,638","4,309,155,528"
13,Financial Assets,Total Assets,"11,945,777,863","12,333,574,539"
14,Equity,Equity Share Capital,"5,456,808,500","5,027,000,000"
15,Equity,Share Premium Reserve,"956,233,911","956,233,911"
16,Equity,Other Reserve & Surplus,"3,153,263,047","3,452,059,583"
17,Equity,Total Equity,"9,566,305,458","9,435,293,494"
18,Financial Liabilities,Long Term Borrowings,"1,636,126","5,364,454"
19,Financial Liabilities,Financial Liabilities_Other Financial Liabilities,"3,432,662",-
20,Financial Liabilities,Deferred Tax Liabilities,"164,023,595","133,127,214"
21,Financial Liabilities,Total Non-Current Liabilities,"169,092,384","138,491,668"
22,Financial Liabilities,Trade Payables,"1,584,583,685","1,508,995,277"
23,Financial Liabilities,Short Term Borrowings,"75,391,983","701,856,485"
24,Financial Liabilities,Financial Liabilities_Other Financial Liabilit...,"42,882,883","59,629,678"
25,Financial Liabilities,Other Current Liabilities,"498,776,009","472,748,681"
26,Financial Liabilities,Provisions,"8,745,461","9,971,139"
27,Financial Liabilities,Income Tax Liabilities (Net),-,"6,588,117"
28,Financial Liabilities,Total Current Liabilities,"2,210,380,021","2,759,789,377"
29,Financial Liabilities,Total Liabilities,"2,379,472,405","2,898,281,045"
30,Financial Liabilities,Total Equity and Liabilities,"11,945,777,863","12,333,574,539"

current file: D:\shivamData\6c7c7-4th-quarter-financial-statement_fy-81-082.pdf

Financial Position,section,Particulars,16th July 2025,15th July 2024
0,Non Current Assets,"Property, Plant & Equipment","3,885,988,681","3,613,074,969"
1,Non Current Assets,Intangible Assets,"11,303,875","3,396,234"
2,Non Current Assets,Investment in Quoted Shares,"131,208,000","119,280,000"
3,Non Current Assets,Investment in Subsidiaries,"4,755,208,800","4,585,208,800"
4,Non Current Assets,Other Non-Current Assets,"37,123,251","34,464,296"
5,Non Current Assets,Total Non Current Assets,"8,820,832,606","8,355,424,299"
6,Current Assets,Inventories,"1,735,417,180","1,874,856,439"
7,Financial Assets,Trade Receivables,"819,967,247","1,126,644,809"
8,Financial Assets,Cash & Cash Equivalent,"651,816,544","240,488,471"
9,Financial Assets,Bank Balance (Other than Cash & Cash Equivalent),"400,000,000","200,000,000"
10,Financial Assets,Others Financial Assets,"26,474,068","34,166,166"
11,Financial Assets,Other Current Assets,"137,570,571","123,901,482"
12,Financial Assets,Income Tax Assets (Net),"6,198,709","15,396,894"
13,Financial Assets,Total Current Assets,"3,777,444,319","3,615,454,260"
14,Financial Assets,Total Assets,"12,598,276,925","11,970,878,560"
15,Equity,Equity Share Capital,"5,456,808,500","5,027,000,000"
16,Equity,Share Premium Reserve,"956,233,911","956,233,911"
17,Equity,Other Reserve & Surplus,"3,876,756,428","3,509,621,193"
18,Equity,Total Equity,"10,289,798,839","9,492,855,104"
19,Financial Liabilities,Long Term Borrowings,"1,738,963","4,710,093"
20,Financial Liabilities,Financial Liabilities_Other Financial Liabilities,"12,160,661","3,432,662"
21,Financial Liabilities,Deferred Tax Liabilities,"200,342,221","158,457,390"
22,Financial Liabilities,Total Non Current Liabilities,"214,241,845","166,600,146"
23,Financial Liabilities,Trade Payables,"1,522,272,214","1,710,448,293"
24,Financial Liabilities,Short Term Borrowings,"8,428,150","68,499,786"
25,Financial Liabilities,Financial Liabilities_Other Financial Liabilit...,"113,050,483","48,481,990"
26,Financial Liabilities,Other Current Liabilities,"436,055,236","472,284,847"
27,Financial Liabilities,Provisions,"14,430,158","11,708,394"
28,Financial Liabilities,Total Current Liabilities,"2,094,236,240","2,311,423,310"
29,Financial Liabilities,Total Liabilities,"2,308,478,086","2,478,023,456"
30,Financial Liabilities,Total Equity and Liabilities,"12,598,276,925","11,970,878,560"

current file: D:\shivamData\7dad4-2nd-quarter-financial-statement_fy079-80.pdf

Financial Position,section,Particulars,14th Jan 2024,14th Jan 2023
0,Non-Current Assets,"Property, Plant & Equipment","3,606,040,403","3,633,904,350"
1,Non-Current Assets,Intangible Assets,"253,397","487,686"
2,Non-Current Assets,Investment in Quoted Shares,"121,665,600","168,542,640"
3,Non-Current Assets,Investment in Subsidiaries,"4,262,135,800","4,262,135,800"
4,Non-Current Assets,Other Non-Current Assets,"34,323,811","33,579,164"
5,Non-Current Assets,Total Non-Current Assets,"8,024,419,011","8,098,649,640"
6,Current Assets,Inventories,"1,700,696,213","1,823,136,191"
7,Financial Assets,Trade Receivables,"1,840,514,041","2,043,884,000"
8,Financial Assets,Cash & Cash Equivalent,"194,057,953","171,867,839"
9,Financial Assets,Others Financial Assets,"267,663,027","26,796,573"
10,Financial Assets,Other Current Assets,"306,224,294","438,688,477"
11,Financial Assets,Total Current Assets,"4,309,155,528","4,504,373,079"
12,Financial Assets,Total Assets,"12,333,574,539","12,603,022,719"
13,Equity,Equity Share Capital,"5,027,000,000","4,400,000,000"
14,Equity,Share Premium Reserve,"956,233,911","956,233,911"
15,Equity,Other Reserve & Surplus,"3,452,059,583","3,832,448,959"
16,Equity,Total Equity,"9,435,293,494","9,188,682,870"
17,Financial Liabilities,Long Term Borrowings,"5,364,454","8,856,652"
18,Financial Liabilities,Deferred Tax Liabilities,"133,127,214","108,068,150"
19,Financial Liabilities,Total Non-Current Liabilities,"138,491,668","116,924,802"
20,Financial Liabilities,Trade Payables,"1,508,995,277","1,496,890,946"
21,Financial Liabilities,Short Term Borrowings,"701,856,485","1,090,491,557"
22,Financial Liabilities,Other Financial Liabilities,"59,629,678","157,543,775"
23,Financial Liabilities,Other Current Liabilities,"472,748,681","541,260,228"
24,Financial Liabilities,Provisions,"9,971,139","3,905,734"
25,Financial Liabilities,Income Tax Liabilities (Net),"6,588,117","7,322,807"
26,Financial Liabilities,Total Current Liabilities,"2,759,789,377","3,297,415,047"
27,Financial Liabilities,Total Liabilities,"2,898,281,045","3,414,339,849"
28,Financial Liabilities,Total Equity and Liabilities,"12,333,574,539","12,603,022,719"

current file: D:\shivamData\a06b5-4rd-quarter-financial-statement_fy-80-081.pdf

Financial Position,section,Particulars,15th July 2024,16th July 2023
0,Non-Current Assets,"Property, Plant & Equipment","3,606,676,545","3,607,472,395"
1,Non-Current Assets,Intangible Assets,"200,178","306,615"
2,Non-Current Assets,Investment in Quoted Shares,"119,280,000","134,786,400"
3,Non-Current Assets,Investment in Subsidiaries,"4,585,208,800","4,262,135,800"
4,Non-Current Assets,Other Non-Current Assets,"34,464,296","34,273,632"
5,Non-Current Assets,Total Non-Current Assets,"8,345,829,820","8,038,974,843"
6,Current Assets,Inventories,"1,871,476,408","1,687,795,030"
7,Financial Assets,Trade Receivables,"1,129,101,138","1,422,942,847"
8,Financial Assets,Cash & Cash Equivalent,"240,488,471","428,781,594"
9,Financial Assets,Others Financial Assets,"17,006,378","181,645,161"
10,Financial Assets,Other Current Assets,"141,061,269","103,124,562"
11,Financial Assets,Total Current Assets,"3,612,852,385","3,824,289,194"
12,Financial Assets,Total Assets,"11,958,682,205","11,863,264,037"
13,Equity,Equity Share Capital,"5,027,000,000","4,400,000,000"
14,Equity,Share Premium Reserve,"956,233,911","956,233,911"
15,Equity,Other Reserve & Surplus,"3,518,798,269","3,940,390,849"
16,Equity,Total Equity,"9,502,032,180","9,296,624,760"
17,Financial Liabilities,Long Term Borrowings,"3,958,597","7,856,771"
18,Financial Liabilities,Deferred Tax Liabilities,"141,917,877","119,290,720"
19,Financial Liabilities,Total Non-Current Liabilities,"145,876,474","127,147,491"
20,Financial Liabilities,Trade Payables,"1,708,718,293","1,582,336,199"
21,Financial Liabilities,Short Term Borrowings,"69,251,283","365,105,430"
22,Financial Liabilities,Other Financial Liabilities,"48,311,140","103,465,119"
23,Financial Liabilities,Other Current Liabilities,"472,882,229","374,094,265"
24,Financial Liabilities,Provisions,"11,610,607","10,022,504"
25,Financial Liabilities,Total Current Liabilities,"2,310,773,552","2,439,491,787"
26,Financial Liabilities,Total Liabilities,"2,456,650,026","2,566,639,277"
27,Financial Liabilities,Total Equity and Liabilities,"11,958,682,205","11,863,264,037"

current file: D:\shivamData\ced52-1th-quarter-financial-statement_fy-080-81.pdf

IndexError: list index out of range

In [89]:
thisFile = financial_statements('D:/shivamData/ced52-1th-quarter-financial-statement_fy-080-81.pdf')
thisFile[0].head(45)

SHIVAM CEMENTS LIMITED
==============================datalist if empty==============================
Financial Position
['Shivam', 'Cements']
Shivam
Cements
==============thCounter============= 2
17th Oct 2023 16th July 2023 17th Oct, 2022
(Ashoj 30, 2080) (Ashad 31, 2080) (Ashoj 31, 2079)
Assets
Non-Current Assets
Property, Plant & Equipment 3,128,084,485 3,249,133,622 3,527,241,703
Intangible Assets 346,792 378,692 595,496
Investment in Quoted Shares 219,851,575 219,851,575 212,571,575
Investment in Subsidiaries 4,262,135,800 4,262,135,800 4,262,135,800
Other Non-Current Assets 55,895,160 34,273,632 35,917,121
Total Non-Current Assets 7,666,313,812 7,765,773,321 8,038,461,694
Current Assets
Inventories 1,879,253,130 1,695,411,083 2,289,412,735
Financial Assets
Trade Receivables 1,687,609,586 1,437,548,798 1,735,991,698
Cash & Cash Equivalent 157,887,088 428,781,594 128,025,858
Others Financial Assets 28,306,501 112,553,904 27,146,321
Other Current Assets 504,940,679 172,288,986 147,714,519
Total Current Assets 4,257,996,984 3,846,584,365 4,328,291,133
Total Assets 11,924,310,796 11,612,357,687 12,366,752,827
Equity & Liabilities
Equity
Equity Share Capital 4,400,000,000 4,400,000,000 4,400,000,000
Share Premium Reserve 956,233,911 956,233,911 956,233,911
Other Reserve & Surplus 3,666,088,463 3,718,416,330 4,151,512,996
Total Equity 9,022,322,374 9,074,650,241 9,507,746,907
Non-Current Liabilities
Financial Liabilities
Long Term Borrowings 4,677,120 6,516,750 8,863,459
Deferred Tax Liabilities 74,723,958 76,836,472 89,220,252
Total Non-Current Liabilities 79,401,078 83,353,222 98,083,710
Current Liabilities
Financial Liabilities
Trade Payables 1,437,053,019 1,581,048,184 1,540,368,704
Short Term Borrowings 969,543,466 366,445,451 672,326,619
Other Financial Liabilities 49,140,890 102,449,393 177,525,409
Other Current Liabilities 355,153,346 390,107,128 357,307,838
Provisions 5,410,570 6,502,818 7,225,470
Income Tax Liabilities (Net) 6,286,053 7,801,249 6,168,170
Total Current Liabilities 2,822,587,345 2,454,354,223 2,760,922,210
Total Liabilities 2,901,988,422 2,537,707,445 2,859,005,920
Total Equity and Liabilities 11,924,310,796 11,612,357,687 12,366,752,827
Una
==============================datalist if empty==============================
Profit & Loss
['Shivam', 'Cements']
Shivam
Cements
==============thCounter============= 2
Upto 1 Qtr 2080-81 Upto 4 Qtr 2079-80 Upto 1 Qtr 2079-80
Income:
Revenue From Operations 1,627,586,921 7,752,793,188 1,534,531,714
Other Income 21,249,358 363,588,791 313,413,803
Total Income 1,648,836,279 8,116,381,978 1,847,945,516
Expenses:
Cost of Sales 1,338,220,771 6,336,893,884 1,229,148,017
Administration Expenses 52,259,341 204,906,206 78,950,132
Selling and Distribution Expenses 173,450,551 682,235,152 127,731,440
Depreciation & Amortization 123,242,738 493,101,441 122,521,640
Finance Cost 15,403,671 96,678,392 19,082,759
Total Expenses 1,702,577,072 7,813,815,074 1,577,433,987
Profit/(Loss) Before Tax (53,740,793) 302,566,904 270,511,529
Current Tax 1,791,837 21,611,679 640,554
Deferred Tax (2,112,514) (21,534,967) (4,894,107)
Net Profit/(Loss) For The Year (53,420,116) 302,490,192 274,765,082
Notes: 1) Figures presented above may vary with the audited figures if instructed by regulators and/or statutory auditors.
2) Figures are regrouped/rearranged/restated wherever necessary for consistent presentation of financial statement.
lwtf]kq btf{ tyf lgisfzg lgodfjnL @)&# sf] cg';"lr !$
-lgod @^ sf] pklgod -!_ ;“u ;DalGwt_ cf=j= @)*).)*! sf] klxnf] q}dfl;s k|ltj]bg
!= ljQLo ljj/0fM
-s_ klxnf] q}dfl;s ;Ddsf] jf;nft, gfkmf—gf]S;fg ;DaGwL ljj/0fM
o; ;+:yfsf] klxnf] q}dfl;s ;Ddsf] gfkmf gf]S;fg tyf jf;nft ;DalGw ljj/0f o;} ;fy k|sflzt ul/Psf] 5 . o; cjwLsf] ;Da4 ;+:yfx?;+u ePsf] sf/f]jf/sf] ljj/0f lgDg cg';f/ /x]sf] 5 M
sf/f]jf/ /sd -d"=c= s/ afx]s_
qm=;+= ;Da4 ;+:yfx?sf] gfd
vl/b ljlqm
! df]8{g O{Gkmfi6«Sr/ k|f=ln= 19,407,495.37
@ c/ljGb ODkf]l/od k|f=ln= 102,486,762.64
# sG:6«Szg ;f]n'zg k|f=ln= 231,639.19
$ kz'klt l;GKofs O08li6«h k|f=ln= 8,135,376.90
% nIdL nfO{d k|f]8S6;\ 36,283.30 102,224.00
^ xf]ª\;L lzjd\ l;d]G6 k|f= ln 374,412,658.81
-v_ k|d'v laQLo cg'kftx?M
k|lt z]o/ cfDbfgL -jflif{s ?=_ k|ltz]o/ g]6jy{ ?= k||ltz]o/ s"n ;DklQsf] d"No ?= t/ntf cg'kft
–4.86 205.05 271.01 1.51
@= Joj:yfksLo ljZn]if0f M
s_ o; cjlwdf ;+:yfsf]] t/ntf nufotsf cGo s'/fx? ;Gtf]ifhgs /x]sf 5g\ .
v_ cfufdL cjlwsf] Joj;flos of]hgf ;DaGwdf Joj:yfkgsf] ljZn]if0ffTds ljj/0fM
ljBdfg cj:yfdf ;+:yfn] pBf]usf] k"0f{ Ifdtf cg';f/sf] pTkfbg / ljqmL ljt/0f u/L pRr u'0f:t/Lo l;d]G6 cfd pkef]Qmfx?sf aLrdf k'¥ofpg] ;DalGw sfo{x? u/L dfgj>f]tsf] sfo{Ifdtfdf
lj:tf/ ug'{sf ;fy} ;dofg's'n Joj;flos sfo{of]hgfsf] th'{df tyf ;f] sf] sfof{Gjog ug]{ nufotsf sfo{df ;+:yf k|ltj4 /x]sf] 5 .
u_ ljutsf] cg'ejaf6 ;+ul7t ;+:yfsf] df}Hbft, gfkmf jf gub k|jfxdf tflTjs c;/ kfg{ ;Sg] 36gf, cj:yf cfbL ePdf ;f] ;DalGw ljZn]if0ffTds ljj/0fM
dx+uf] a}+s Jofhb/, t/ntfsf] ;+s'rg, ljZj ahf/df sf]O{nf, l8h]n nufPtsf ;fdfgx?sf] cToflws d"No a[l4sf] k|efj, ;d]tsf sf/0f pTkfbg nfut a[l4 x'g k'u]sf], ljsf; lgdf{0fsf sfddf
cfPsf] l;lyntf oyfjt /x]sf], g]kfndf dfusf] t'ngfdf l;d]G6sf] pTkfbg cToflws /x]sf], lalqm d'Nodf x|f; ePsf] cj:yf ;d]tn] ubf{ ;+:yfn] cfkm\gf] pTkfbg Ifdtfsf] k"0f{ pkof]u ub{} ahf/
k|j{4{g / ahf/ lj:tf/;+u ;DalGwt sfo{x?nfO{ cem k|efjsf/L ?kdf ;~rfng ug{] gLlt cjnDag u/L ;+:yfnfO{ c;/ kg{ ;Sg] s'/fx?sf] ;"Id cWoog / ljZn]if0f ub{} s'zn sfo{gLlt tyf
r':t Joj:yfkg dfkm{t u|fxs ;+/If0f gLltnfO{ sfod} /fVb} cfFpbf lbgdf tflTjs gsf/fTds c;/ kfg{ ;Sg] 36gf jf cj:yf cfpg glbg cfjZos gLlt lgodsf] th'{df u/L p2]Zo adf]lhdsf
sfdx? ;+rfng ub{} cl3 a9\g] gLlt lnOPsf] 5 . gub k|jfx nufotsf s'/fx?df tTsfn tflTjs c;/ kg{ ;Sg] 36gf, cj:yf eg] kfOPsf] 5}g .
#= sfg"gL sf/jfxL ;DalGw ljj/0fM -o; ;+:yfn] jf ;+:yfsf] lj?4 s'g} d'2f bfo/ ePsf] eP ;f]sf] hfgsf/L_M–
-s_ cfkm\gf] Joj;fo;+u ;DalGwt sf/f]jf/, vr{ nufotsf ljifodf eP u/]sf s]xL lz{ifsdf >L 7"nf s/bftf sfof{noaf6 ePsf ;+zf]lwt s/ lgwf{/0f cfb]zsf lj?4 sDkgLn] k|zf;sLo
k'g/fjnf]sgsf nflu cfGtl/s /fh:j ljefusf dxflgb{]zsHo" ;dIf tyf >L /fh:j Gofoflws/0f sf7df8f}+ ;dIf k'g/fj]bg u/]sf]df ;f] ljifox? ljrf/flwg /x]sf 5g .
-v_ o; sDkgLnfO{ ljutdf nf]8;]l8ª x'bfsf] avt g]kfn ljB't k|flws/0faf6 x/]s lbg pBf]usf] ljB't s6f}tL u/L nf]8;]l8ª ug]{ u/]sf] oyfy{ cj:yf /x]sf] ePtf klg cyf{t ;'ljwf g} pkef]u gu/]
sf] cj:yfdf ;d]t 8]l8s]6]8 lkm8/ dfkm{t ljB't pkef]u u/]sf] egL 8]l8s]6]8 b/df ljn ug{] tyf 5'6 ljn hf/L ug{] / aSof}tf /sd bflvnf ug'{ cGoyf nfO{g sfl6g]5 egL k6s k6s kqfrf/
u/]sf] x'+bf cGofo k"j{ssf] sfo{ x'g hfg] ;DefjgfnfO{ Wofgdf /fvL sfg"gL pkrf/sf nflu >L dsjfgk'/ lhNnf cbfnt ;dIf g]= lj= k|f= P]g @)$) adf]lhd g]kfn ljB't k|flws/0fsf lj?4
lkm/fb kq btf{ u/]sf]df ljrf/flwg /x]sf] 5 . ;fy} ;Ddflgt >L kf6g pRr cbfntsf] x]6f}8f Ohnf;af6 hf/L ePsf] nfO{g gsf6\g' eGg] ;d]tsf] cGt/sflng cfb]z sfod /xg'sf ;fy} ljB't
dx;'n ljjfbsf ljifodf ;Ddflgt >L ;jf]{Rj cbfntdf l/6 lgj]bg ;d]t ljrf/flwg /x]sf 5g . ;fy} g]kfn ljB't k|flws/0fn] c;'n ug{ gldNg] 8]l8s]6]8 b/sf] lan, kq agfO{ kqfrf/ u/L
aSof}tf /sd e'QmfgL ug'{ elg kqfrf/ ubf{ hl/jfgf jfkt 7"nf] /sd ;d]t hf]8L hfgsf/L u/fpg] u/]sf] 5 .
-u_ sDkgLn] l;d]G6 laqmL ug{ lgo'Qm u/]sf ljt/s / l;d]G6 vl/bstf{ ;+:yfx?n] ;dodf /sd e'QmfgL gu/]sf] ljifodf To:tf s]lx ;+:yf Pad\ JolQm ;d]tsf lj?4 /sd c;'nLsf nflu >L sf7df8f}+
lhNnf cbfntdf lkm/fb bfo/ u/]sf]df pQm d'Bfx? ljrf/flwg /x]sf 5g .
3_ jfudtL k|b]z ;/sf/sf] cfly{s P]g @)&& / )&* af6 l;d]G6sf] ljlqmdf )=@% k|ltzt ljlqm s/ ;/x k|fs[lts ;|f]t s/ nufpg] Joj:yf ;+ljwfg / ;+l3o sfg"g ;+u aflemPsf] x'Fbf P]gsf pQm
Joj:yf ab/ ug{ dfu u/L ;jf]{Rr cbfnt ;dIf l/6 lgj]bg bfo/ ePsf]df ljrf/flwg /x]sf] 5 .
ª_ sDkgLsf s'g} klg ;+rfnssf lj?4 cfly{s ck/fw u/]sf] ljifodf s'g} d'4f bfo/ u/]sf] jf ePsf] jf/] s'g} hfgsf/L k|fKt ePsf] 5}g .
$= ;+:yfsf] z]o/ sf/f]jf/ tyf k|ult ljZn]if0fM
-s_ lwtf]kq ahf/df ePsf] o; ;+:yfsf] z]o/sf] sf/f]jf/df x'g] ptf/ r9fj v'Nnf ahf/sf] l;4fGt cg'?k x'g] u/]sf]5 .
-v_ o; q}df; cjlwsf] z]o/sf] clwstd, Go"gtd, clGtd d"No, sf/f]jf/ ePsf] lbg / z]o/ sf/f]jf/ ;+Vof M
clwstd d"No ?= Go"gtd d"No ?= clGtd d"No ?= sf/f]jf/ lbg sf/f]jf/ z]o/ ;+Vof
^&%.)) $*!.)) %)#.)) ^! &!,*&,$^& yfg
%= ;d:of tyf r'gf}tLM
a}+s Jofhb/ g36\g', dfusf] t'ngfdf g]kfndf l;d]G6sf] pTkfbg Ifdtf cToflws x'g', ljsf; lgdf{0f;+u ;DaGwLt ;/sf/L kl/of]hgfx?df rfn' cf=a=sf nflu 5'6\ofO{Psf] ah]6 vr{ x'g g;Sg' cyf{t
7]Ssf k|lqmofdf g} klxnf] q}dfl;s ;dfKt x'g k'u]sf] cj:yf 5 eg] ;f]xL sf/0f ah]6 Go"g dfqfdf vr{ x'g] u/]sf] nufPtsf sf/0faf6 r'gf}tL pTkGg x'g] cfz+sf 5 . sf]Onf, l8h]n, k]6«f]n, nufPtsf
OGwgsf] d'No, ?;–o'qm]g o'4 ;d]tsf] k|efjsf sf/0f cToflws dfqfdf a[l4 ePsf] nfdf] ;do;Dd klg d"No 36]sf] 5}g, pTkfbg ljlqm ubf{ lalqm d"Nodf x|f; ePsf] sf/0f d'gfkmfdf clea[l4 x'g' kg]{df
geO{ x|f; eO{ gf]S;fgL x'g k'u]sf] 5 . ahf/df cfd u|fxsx? Dffem o; ;+:yfsf] pTkfbgnfO{ k|efjzfnL agfO{ xfnsf] ahf/ lx:;f sfod} /fvL yk ahf/ lx:;f cf]u6\g ;f]xL cg'?ksf] gLlt, /0fgLlt
cjnDag ul/ ;+:yfn] laqmL kl5 pknJw u/fpg] lgMZf'Ns k|fljlws ;]jfx?sf] lj:tf/, dfgj ;+zfwgsf] bIftfdf clea[l4 / r':t Joj:yfkg, vr{df ldtJolotf ckgfO{ sfo{ cjnDjg ul/Psf] 5 .
^= ;+:yfut ;'zf;gM
;+:yfut ;'zf;g clej[l4sf nflu ;+:yfsf] Joj:yfkg cfGtl/s lgoGq0f k|0ffnL Jojl:yt ug{], cfGtl/s n]vfk/LIf0f sfo{nfO{ yk k|efjsf/L agfpg], sf/f]jf/nfO{ r':t, l56f], 5l/tf] agfpg sf/f]jf/
df cfs{lift x'g] P]g, sfg"g tyf lgodgsf/L lgsfoaf6 hf/L ePsf gLlt, lgb{]zgx? Kffngf u/L ;+:yf ;+rfng ul/Psf] 5 .
&= ;To tYotfsf ;DaGwdf k|jGw lgb]{zssf] pb\3f]if0fM
o; k|ltj]bgdf pNn]lvt hfgsf/L tyf ljj/0fx?sf] z'4tf ;DaGwdf d JolQmut ?kdf pQ/bfloTj lnG5' . ;fy} d of] pb\3f]if0f ub{5' sL d}n] hfg] a'em];Dd o; k|ltj]bgdf pNn]lvt ljj/0fx? ;To,
tYo / k"0f{ 5g . nufgLstf{nfO{ ;';"lrt lg0f{o lng cfjZos s'g} ljj/0f jf ;"rgf tyf hfgsf/Lx? n'sfO{Psf] 5}g .
==============================datalist if empty==============================

IndexError: list index out of range